apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: restservicejson-deployment
spec:
  selector:
    matchLabels:
      app: restservice
  replicas: 1
  template:
    metadata:
      labels:
        app: restservice
    spec:
      containers:
        - name: restservice
          image: srinivasjastijava/services:srinivasrestservicejson
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              hostPort: 8080



